### ISSUE TITLE
[Ticket]: Dockerizing the Backend/API

### ISSUE THREAD

**Issue by danielschuster-muc** [danielschuster-muc/potter-db#740] opened 2023-09-30 13:44 UTC
### Project

API (api.potterdb.com)

### Describe the ticket you want to create

To simplify the process of contributing to our project, we're embarking on the journey of Dockerizing our backend/API. This means that contributors won't need to install Ruby or deal with complex setup procedures. Instead, they can effortlessly spin up the project environment using Docker containers.

### Acceptance Criteria

- [ ] Create `docker-compose.yml` and `Dockerfile` to define the backend container.
- [ ] Include all necessary dependencies and configurations within the Docker container (e.g. Ruby on Rails and PostgreSQL)
- [ ] Update the [README file](https://github.com/danielschuster-muc/potter-db/blob/master/backend/README.md) to explain the new setup with docker.

### Additional Details

https://docs.docker.com/get-started/

**Comment by sirish123** [comment] 2023-10-01 07:03
hey i would like to work on this issue could you assign it to me

**Comment by sirish123** [comment] 2023-10-05 07:38
rails db:create
/home/sirish/.rbenv/versions/3.1.2/bin/ruby: warning: shebang line ending with \r may cause problems
We could not find your database: postgres. Which can be found in the database configuration file located at config/database.yml.

To resolve this issue:

- Did you create the database for this app, or delete it? You may need to create your database.
- Has the database name changed? Check your database.yml config has the correct database name.

To create your database, run:

        bin/rails db:create
Couldn't create 'potter_db_api_development' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: We could not find your database: postgres. Which can be found in the database configuration file located at config/database.yml.

To resolve this issue:

- Did you create the database for this app, or delete it? You may need to create your database.
- Has the database name changed? Check your database.yml config has the correct database name.

To create your database, run:

        bin/rails db:create


Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "sirish" does not exist

Tasks: TOP => db:create
(See full trace by running task with --trace) 

 should I change anything in the yml file?

**Comment by sirish123** [comment] 2023-10-06 10:50
![image](https://github.com/danielschuster-muc/potter-db/assets/81297089/6b1c8ebf-33aa-4d0f-bd29-c27856f9334c)
Hey daniel! after starting rails we are redirected to https://docs.potterdb.com/ is that how its supposed to work?

**Comment by danielschuster-muc** [comment] 2023-10-06 12:03
Yes, its supposed to redirect to the docs. You have to use one of the endpoints, e.g. `/v1/characters`.

**Closed** 2023-10-12 12:50 UTC
Labels: enhancement, good first issue, api, hacktoberfest
